// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO7WDblbI7O9x7ui2E56ZeuQK9QUm2cq4',
    appId: '1:917143618214:web:abd904aab53628028cea67',
    messagingSenderId: '917143618214',
    projectId: 'pab-ii-f9a0a',
    authDomain: 'pab-ii-f9a0a.firebaseapp.com',
    databaseURL: 'https://pab-ii-f9a0a-default-rtdb.firebaseio.com',
    storageBucket: 'pab-ii-f9a0a.firebasestorage.app',
    measurementId: 'G-M0Q8JRWPZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJbUUuPTZ7PzG7ET84skHww41JFb2Xzw',
    appId: '1:917143618214:android:7cba858c0fb69af38cea67',
    messagingSenderId: '917143618214',
    projectId: 'pab-ii-f9a0a',
    databaseURL: 'https://pab-ii-f9a0a-default-rtdb.firebaseio.com',
    storageBucket: 'pab-ii-f9a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4r45bYEwVBxZXfezHLQlc2UDz8dCo9FI',
    appId: '1:917143618214:ios:fa5f91dd4d18246a8cea67',
    messagingSenderId: '917143618214',
    projectId: 'pab-ii-f9a0a',
    databaseURL: 'https://pab-ii-f9a0a-default-rtdb.firebaseio.com',
    storageBucket: 'pab-ii-f9a0a.firebasestorage.app',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4r45bYEwVBxZXfezHLQlc2UDz8dCo9FI',
    appId: '1:917143618214:ios:fa5f91dd4d18246a8cea67',
    messagingSenderId: '917143618214',
    projectId: 'pab-ii-f9a0a',
    databaseURL: 'https://pab-ii-f9a0a-default-rtdb.firebaseio.com',
    storageBucket: 'pab-ii-f9a0a.firebasestorage.app',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO7WDblbI7O9x7ui2E56ZeuQK9QUm2cq4',
    appId: '1:917143618214:web:a780ce14064770488cea67',
    messagingSenderId: '917143618214',
    projectId: 'pab-ii-f9a0a',
    authDomain: 'pab-ii-f9a0a.firebaseapp.com',
    databaseURL: 'https://pab-ii-f9a0a-default-rtdb.firebaseio.com',
    storageBucket: 'pab-ii-f9a0a.firebasestorage.app',
    measurementId: 'G-CWGZQPGYBC',
  );
}
