// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO7WDblbI7O9x7ui2E56ZeuQK9QUm2cq4',
    appId: '1:917143618214:web:a780ce14064770488cea67',
    messagingSenderId: '917143618214',
    projectId: 'pab-ii-f9a0a',
    authDomain: 'pab-ii-f9a0a.firebaseapp.com',
    databaseURL: 'https://pab-ii-f9a0a-default-rtdb.firebaseio.com',
    storageBucket: 'pab-ii-f9a0a.firebasestorage.app',
    measurementId: 'G-CWGZQPGYBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJbUUuPTZ7PzG7ET84skHww41JFb2Xzw',
    appId: '1:917143618214:android:1fc552df013fcdc08cea67',
    messagingSenderId: '917143618214',
    projectId: 'pab-ii-f9a0a',
    databaseURL: 'https://pab-ii-f9a0a-default-rtdb.firebaseio.com',
    storageBucket: 'pab-ii-f9a0a.firebasestorage.app',
  );
}
